export const africanLanguages = [
  "English (Nigerian)",
  "English (South African)",
  "English (Kenyan)",
  "English (Ghanaian)",
  "English (Liberian)",
  "English (Sierra Leonean)",
  "English (Ugandan)",
  "French (African)",
  "Portuguese (African)",
  "Arabic (North African)",
  "Arabic (Sudanese)",
  "Swahili",
  "Yoruba",
  "Hausa",
  "Igbo",
  "Zulu",
  "Xhosa",
  "Amharic",
  "Oromo",
  "Somali",
  "Tigrinya",
  "Shona",
  "Ndebele",
  "Chichewa",
  "Kinyarwanda",
  "Kirundi",
  "Luganda",
  "Lingala",
  "Kongo",
  "Tshiluba",
  "Bambara",
  "Wolof",
  "Fulfulde (Fula)",
  "Mandinka",
  "Akan (Twi)",
  "Ewe",
  "Ga",
  "Dagbani",
  "Sesotho",
  "Setswana",
  "Sepedi",
  "Afrikaans",
  "Malagasy",
  "Mauritian Creole",
  "Seychellois Creole",
  "Krio",
  "Pidgin (Nigerian)",
  "Pidgin (Cameroonian)",
  "Pidgin (Ghanaian)"
];
