-- Create service_type enum for gigs
do $$
begin
  create type service_type as enum (
    'studio_only',
    'raw_recording',
    'produced_and_mixed',
    'producer_only'
  );
exception
  when duplicate_object then null;
end $$;

-- Create production_assignment_type enum
do $$
begin
  create type production_assignment_type as enum (
    'vocal_production',
    'mixing',
    'mastering',
    'full_production'
  );
exception
  when duplicate_object then null;
end $$;

-- Create production_assignment_status enum
do $$
begin
  create type production_assignment_status as enum (
    'pending',
    'accepted',
    'in_progress',
    'revision_requested',
    'completed',
    'cancelled'
  );
exception
  when duplicate_object then null;
end $$;

-- Create audio_deliverable_type enum
do $$
begin
  create type audio_deliverable_type as enum (
    'raw',
    'produced',
    'final',
    'revision'
  );
exception
  when duplicate_object then null;
end $$;

-- Create audio_deliverable_status enum
do $$
begin
  create type audio_deliverable_status as enum (
    'pending',
    'approved',
    'rejected',
    'pending_revision'
  );
exception
  when duplicate_object then null;
end $$;

-- Add producer fields to users table
alter table public.users add column if not exists is_producer boolean default false;
alter table public.users add column if not exists producer_skills text[]; -- Array of skills
alter table public.users add column if not exists production_rate_per_hour numeric(10, 2);
alter table public.users add column if not exists production_equipment text;
alter table public.users add column if not exists turnaround_time_days integer;
alter table public.users add column if not exists portfolio_samples jsonb; -- Array of {title, url, type}

-- Add service_type to gigs table
alter table public.gigs add column if not exists service_type service_type default 'studio_only';
alter table public.gigs add column if not exists production_notes text;
alter table public.gigs add column if not exists requires_producer boolean default false;
alter table public.gigs add column if not exists assigned_producer_id uuid references public.users(id) on delete set null;

-- Create production_services table
create table if not exists public.production_services (
  id bigint generated by default as identity primary key,
  producer_id uuid references public.users(id) on delete cascade not null,
  title text not null,
  description text,
  assignment_type production_assignment_type not null,
  rate_per_hour numeric(10, 2) not null,
  turnaround_days integer,
  featured_work_urls text[],
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for production_services
alter table public.production_services enable row level security;

-- Policies for production_services
create policy "Production services are viewable by everyone" 
  on public.production_services for select 
  using ( is_active = true );

create policy "Producers can manage own services" 
  on public.production_services for insert 
  with check ( auth.uid() = producer_id );

create policy "Producers can update own services" 
  on public.production_services for update 
  using ( auth.uid() = producer_id );

-- Create production_assignments table
create table if not exists public.production_assignments (
  id bigint generated by default as identity primary key,
  gig_id bigint references public.gigs(id) on delete cascade not null,
  producer_id uuid references public.users(id) on delete cascade not null,
  assignment_type production_assignment_type not null,
  status production_assignment_status default 'pending',
  rate_amount numeric(10, 2),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  feedback text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for production_assignments
alter table public.production_assignments enable row level security;

-- Policies for production_assignments
create policy "Producers can view own assignments" 
  on public.production_assignments for select 
  using ( auth.uid() = producer_id );

create policy "Clients can view assignments for their gigs" 
  on public.production_assignments for select 
  using ( exists ( select 1 from public.gigs where gigs.id = production_assignments.gig_id and gigs.client_id = auth.uid() ) );

create policy "Producers can accept assignments" 
  on public.production_assignments for update 
  using ( auth.uid() = producer_id );

-- Create audio_deliverables table
create table if not exists public.audio_deliverables (
  id bigint generated by default as identity primary key,
  gig_id bigint references public.gigs(id) on delete cascade not null,
  talent_id uuid references public.users(id) on delete cascade,
  producer_id uuid references public.users(id) on delete cascade,
  audio_type audio_deliverable_type not null,
  file_url text not null,
  version_number integer default 1,
  status audio_deliverable_status default 'pending',
  feedback text,
  created_by uuid references public.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for audio_deliverables
alter table public.audio_deliverables enable row level security;

-- Policies for audio_deliverables
create policy "Talents can view own deliverables" 
  on public.audio_deliverables for select 
  using ( auth.uid() = talent_id or auth.uid() = producer_id );

create policy "Clients can view deliverables for their gigs" 
  on public.audio_deliverables for select 
  using ( exists ( select 1 from public.gigs where gigs.id = audio_deliverables.gig_id and gigs.client_id = auth.uid() ) );

create policy "Users can upload deliverables" 
  on public.audio_deliverables for insert 
  with check ( auth.uid() = talent_id or auth.uid() = producer_id );

-- Storage Bucket for audio deliverables
insert into storage.buckets (id, name, public) values ('audio-deliverables', 'audio-deliverables', false) on conflict do nothing;

-- Storage Policies for audio deliverables (private, auth-only)
create policy "Authenticated users can upload audio deliverables" on storage.objects 
  for insert 
  with check ( bucket_id = 'audio-deliverables' and auth.role() = 'authenticated' );

create policy "Users can view own audio deliverables" on storage.objects 
  for select 
  using ( bucket_id = 'audio-deliverables' and auth.role() = 'authenticated' );

-- Create producer_ratings table
create table if not exists public.producer_ratings (
  id bigint generated by default as identity primary key,
  producer_id uuid references public.users(id) on delete cascade not null,
  client_id uuid references public.users(id) on delete cascade not null,
  gig_id bigint references public.gigs(id) on delete cascade not null,
  rating numeric(3, 2) check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for producer_ratings
alter table public.producer_ratings enable row level security;

-- Policies for producer_ratings
create policy "Ratings are viewable by everyone" 
  on public.producer_ratings for select 
  using ( true );

create policy "Clients can rate producers" 
  on public.producer_ratings for insert 
  with check ( auth.uid() = client_id );
