-- PART 3: Create tables
-- Run this in Supabase SQL Editor

-- Create production_services table
CREATE TABLE IF NOT EXISTS public.production_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producer_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  assignment_type production_assignment_type NOT NULL,
  rate_per_hour NUMERIC(10, 2) NOT NULL,
  turnaround_days INTEGER,
  featured_work_urls TEXT[],
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.production_services ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Production services are viewable by everyone" ON public.production_services;
CREATE POLICY "Production services are viewable by everyone" 
  ON public.production_services FOR SELECT 
  USING ( is_active = true );

DROP POLICY IF EXISTS "Producers can manage own services" ON public.production_services;
CREATE POLICY "Producers can manage own services" 
  ON public.production_services FOR INSERT 
  WITH CHECK ( auth.uid() = producer_id );

DROP POLICY IF EXISTS "Producers can update own services" ON public.production_services;
CREATE POLICY "Producers can update own services" 
  ON public.production_services FOR UPDATE 
  USING ( auth.uid() = producer_id );

-- Create production_assignments table
CREATE TABLE IF NOT EXISTS public.production_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gig_id BIGINT REFERENCES public.gigs(id) ON DELETE CASCADE NOT NULL,
  producer_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  assignment_type production_assignment_type NOT NULL,
  status production_assignment_status DEFAULT 'pending',
  rate_amount NUMERIC(10, 2),
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  feedback TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.production_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Producers can view own assignments" ON public.production_assignments;
CREATE POLICY "Producers can view own assignments" 
  ON public.production_assignments FOR SELECT 
  USING ( auth.uid() = producer_id );

DROP POLICY IF EXISTS "Clients can view assignments for their gigs" ON public.production_assignments;
CREATE POLICY "Clients can view assignments for their gigs" 
  ON public.production_assignments FOR SELECT 
  USING ( EXISTS ( SELECT 1 FROM public.gigs WHERE gigs.id = production_assignments.gig_id AND gigs.client_id = auth.uid() ) );

DROP POLICY IF EXISTS "Producers can accept assignments" ON public.production_assignments;
CREATE POLICY "Producers can accept assignments" 
  ON public.production_assignments FOR UPDATE 
  USING ( auth.uid() = producer_id );

-- Create audio_deliverables table
CREATE TABLE IF NOT EXISTS public.audio_deliverables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gig_id BIGINT REFERENCES public.gigs(id) ON DELETE CASCADE NOT NULL,
  talent_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  producer_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  audio_type audio_deliverable_type NOT NULL,
  status audio_deliverable_status DEFAULT 'pending',
  audio_url TEXT NOT NULL,
  duration_seconds INTEGER,
  notes TEXT,
  revision_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.audio_deliverables ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Talent can view own deliverables" ON public.audio_deliverables;
CREATE POLICY "Talent can view own deliverables" 
  ON public.audio_deliverables FOR SELECT 
  USING ( auth.uid() = talent_id OR auth.uid() = producer_id );

DROP POLICY IF EXISTS "Talent can upload deliverables" ON public.audio_deliverables;
CREATE POLICY "Talent can upload deliverables" 
  ON public.audio_deliverables FOR INSERT 
  WITH CHECK ( auth.uid() = talent_id );

DROP POLICY IF EXISTS "Producer can upload deliverables" ON public.audio_deliverables;
CREATE POLICY "Producer can upload deliverables" 
  ON public.audio_deliverables FOR INSERT 
  WITH CHECK ( auth.uid() = producer_id );

DROP POLICY IF EXISTS "Talent can update own deliverables" ON public.audio_deliverables;
CREATE POLICY "Talent can update own deliverables" 
  ON public.audio_deliverables FOR UPDATE 
  USING ( auth.uid() = talent_id );
