-- =============================================================================
-- COMPLETE MIGRATION: VoiceBox Africa Studio Producer Setup
-- =============================================================================
-- This file sets up the complete producer system including:
-- 1. Enum types
-- 2. Column additions to users and gigs tables
-- 3. New tables (production_services, production_assignments, audio_deliverables)
-- 4. VoiceBox Africa Studio as the official producer
-- =============================================================================

-- ============================================
-- PART 1: Create Enums (if they don't exist)
-- ============================================

-- Create service_type enum for gigs
DO $$
BEGIN
  CREATE TYPE service_type AS ENUM (
    'studio_only',
    'raw_recording',
    'produced_and_mixed',
    'producer_only'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Create production_assignment_type enum
DO $$
BEGIN
  CREATE TYPE production_assignment_type AS ENUM (
    'vocal_production',
    'mixing',
    'mastering',
    'full_production'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Create production_assignment_status enum
DO $$
BEGIN
  CREATE TYPE production_assignment_status AS ENUM (
    'pending',
    'accepted',
    'in_progress',
    'revision_requested',
    'completed',
    'cancelled'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Create audio_deliverable_type enum
DO $$
BEGIN
  CREATE TYPE audio_deliverable_type AS ENUM (
    'raw',
    'produced',
    'final',
    'revision'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Create audio_deliverable_status enum
DO $$
BEGIN
  CREATE TYPE audio_deliverable_status AS ENUM (
    'pending',
    'approved',
    'rejected',
    'pending_revision'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- PART 2: Add columns to users table
-- ============================================

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_producer BOOLEAN DEFAULT false;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS producer_skills TEXT[];
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS production_rate_per_hour NUMERIC(10, 2);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS production_equipment TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS turnaround_time_days INTEGER;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS portfolio_samples JSONB;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS pricing_matrix JSONB;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_official_producer BOOLEAN DEFAULT false;

-- ============================================
-- PART 3: Add columns to gigs table
-- ============================================

ALTER TABLE public.gigs ADD COLUMN IF NOT EXISTS service_type service_type DEFAULT 'studio_only';
ALTER TABLE public.gigs ADD COLUMN IF NOT EXISTS production_notes TEXT;
ALTER TABLE public.gigs ADD COLUMN IF NOT EXISTS requires_producer BOOLEAN DEFAULT false;
ALTER TABLE public.gigs ADD COLUMN IF NOT EXISTS assigned_producer_id UUID REFERENCES public.users(id) ON DELETE SET NULL;

-- ============================================
-- PART 4: Create production_services table
-- ============================================

CREATE TABLE IF NOT EXISTS public.production_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producer_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  assignment_type production_assignment_type NOT NULL,
  rate_per_hour NUMERIC(10, 2) NOT NULL,
  turnaround_days INTEGER,
  featured_work_urls TEXT[],
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.production_services ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Production services are viewable by everyone" ON public.production_services;
CREATE POLICY "Production services are viewable by everyone" 
  ON public.production_services FOR SELECT 
  USING ( is_active = true );

DROP POLICY IF EXISTS "Producers can manage own services" ON public.production_services;
CREATE POLICY "Producers can manage own services" 
  ON public.production_services FOR INSERT 
  WITH CHECK ( auth.uid() = producer_id );

DROP POLICY IF EXISTS "Producers can update own services" ON public.production_services;
CREATE POLICY "Producers can update own services" 
  ON public.production_services FOR UPDATE 
  USING ( auth.uid() = producer_id );

-- ============================================
-- PART 5: Create production_assignments table
-- ============================================

CREATE TABLE IF NOT EXISTS public.production_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gig_id BIGINT REFERENCES public.gigs(id) ON DELETE CASCADE NOT NULL,
  producer_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  assignment_type production_assignment_type NOT NULL,
  status production_assignment_status DEFAULT 'pending',
  rate_amount NUMERIC(10, 2),
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  feedback TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.production_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Producers can view own assignments" ON public.production_assignments;
CREATE POLICY "Producers can view own assignments" 
  ON public.production_assignments FOR SELECT 
  USING ( auth.uid() = producer_id );

DROP POLICY IF EXISTS "Clients can view assignments for their gigs" ON public.production_assignments;
CREATE POLICY "Clients can view assignments for their gigs" 
  ON public.production_assignments FOR SELECT 
  USING ( EXISTS ( SELECT 1 FROM public.gigs WHERE gigs.id = production_assignments.gig_id AND gigs.client_id = auth.uid() ) );

DROP POLICY IF EXISTS "Producers can accept assignments" ON public.production_assignments;
CREATE POLICY "Producers can accept assignments" 
  ON public.production_assignments FOR UPDATE 
  USING ( auth.uid() = producer_id );

-- ============================================
-- PART 6: Create audio_deliverables table
-- ============================================

CREATE TABLE IF NOT EXISTS public.audio_deliverables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gig_id BIGINT REFERENCES public.gigs(id) ON DELETE CASCADE NOT NULL,
  talent_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  producer_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  audio_type audio_deliverable_type NOT NULL,
  status audio_deliverable_status DEFAULT 'pending',
  audio_url TEXT NOT NULL,
  duration_seconds INTEGER,
  notes TEXT,
  revision_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.audio_deliverables ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Talent can view own deliverables" ON public.audio_deliverables;
CREATE POLICY "Talent can view own deliverables" 
  ON public.audio_deliverables FOR SELECT 
  USING ( auth.uid() = talent_id OR auth.uid() = producer_id );

DROP POLICY IF EXISTS "Talent can upload deliverables" ON public.audio_deliverables;
CREATE POLICY "Talent can upload deliverables" 
  ON public.audio_deliverables FOR INSERT 
  WITH CHECK ( auth.uid() = talent_id );

DROP POLICY IF EXISTS "Producer can upload deliverables" ON public.audio_deliverables;
CREATE POLICY "Producer can upload deliverables" 
  ON public.audio_deliverables FOR INSERT 
  WITH CHECK ( auth.uid() = producer_id );

DROP POLICY IF EXISTS "Talent can update own deliverables" ON public.audio_deliverables;
CREATE POLICY "Talent can update own deliverables" 
  ON public.audio_deliverables FOR UPDATE 
  USING ( auth.uid() = talent_id );

-- ============================================
-- PART 7: Create constraints and triggers
-- ============================================

-- Create constraint: only one official producer can exist
CREATE OR REPLACE FUNCTION check_single_official_producer()
RETURNS TRIGGER AS $$
BEGIN
  IF new.is_official_producer = true THEN
    IF EXISTS (
      SELECT 1 FROM public.users 
      WHERE is_official_producer = true 
      AND id != new.id
    ) THEN
      RAISE EXCEPTION 'Only one official VoiceBox producer account is allowed';
    END IF;
  END IF;
  RETURN new;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS enforce_single_official_producer ON public.users;
CREATE TRIGGER enforce_single_official_producer
  BEFORE INSERT OR UPDATE ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION check_single_official_producer();

-- ============================================
-- PART 8: Create VoiceBox Africa Studio producer
-- ============================================
-- IMPORTANT: Replace 'YOUR_STUDIO_USER_ID' with the actual UUID from Supabase Auth
-- 
-- To create the VoiceBox Studio account:
-- 1. Go to Supabase Dashboard > Authentication > Users
-- 2. Create a new user with email: studio@voiceboxafrica.com
-- 3. Copy the user's UUID
-- 4. Replace 'YOUR_STUDIO_USER_ID' below with that UUID
-- 5. Run this migration

-- Example (replace with actual UUID):
-- INSERT INTO public.users (
--   id,
--   email,
--   name,
--   role,
--   bio,
--   is_producer,
--   is_official_producer,
--   is_available,
--   producer_skills,
--   production_rate_per_hour,
--   turnaround_time_days,
--   pricing_matrix,
--   created_at,
--   updated_at
-- ) VALUES (
--   'YOUR_STUDIO_USER_ID'::uuid,
--   'studio@voiceboxafrica.com',
--   'VoiceBox Africa Studio',
--   'producer',
--   'Official VoiceBox Africa audio production studio. Professional mixing, mastering, and full production services.',
--   true,
--   true,
--   true,
--   ARRAY['mixing', 'mastering', 'vocal_production', 'full_production'],
--   75,
--   3,
--   '{
--     "studio_only": {"rate_per_hour": 75, "base_rate": 0, "currency": "USD"},
--     "raw_recording": {"rate_per_hour": 75, "base_rate": 0, "currency": "USD"},
--     "produced_and_mixed": {"rate_per_hour": 100, "base_rate": 0, "currency": "USD"},
--     "producer_only": {"rate_per_hour": 125, "base_rate": 500, "currency": "USD"}
--   }'::jsonb,
--   now(),
--   now()
-- ) ON CONFLICT (id) DO NOTHING;

-- ============================================
-- DONE!
-- ============================================
